import { useEffect, useState } from 'react';
import { CheckCircle2, FolderTree, Plus, Save, X } from 'lucide-react';
import { apiGet, apiPatch, apiPost } from '../../lib/apiClient.js';

const blank = { name: '', slug: '', description: '', sortOrder: 0, status: 'published' };

export default function AdminCategoriesPage() {
  const [tab, setTab] = useState('categories');
  const [rows, setRows] = useState([]);
  const [form, setForm] = useState(null);
  const [state, setState] = useState({ status: 'loading', error: '', message: '' });
  const load = () => apiGet('/api/v1/taxonomy').then((payload) => { setRows(payload[tab] || []); setState({ status: 'ready', error: '', message: '' }); }).catch((error) => setState({ status: 'error', error: error.message, message: '' }));
  useEffect(() => { load(); }, [tab]);
  const update = (field) => (event) => setForm((current) => ({ ...current, [field]: event.target.value }));
  const save = async (event) => { event.preventDefault(); setState({ status: 'saving', error: '', message: '' }); try { if (form.id) await apiPatch('/api/v1/taxonomy/' + tab + '/' + form.id, form); else await apiPost('/api/v1/taxonomy/' + tab, form); setForm(null); setState({ status: 'saved', error: '', message: (tab === 'categories' ? 'Category' : 'Brand') + ' saved.' }); load(); } catch (error) { setState({ status: 'error', error: error.message, message: '' }); } };
  const archive = async (id) => { try { await apiPost('/api/v1/taxonomy/' + tab + '/' + id + '/archive', {}); load(); } catch (error) { setState({ status: 'error', error: error.message, message: '' }); } };
  return <section className="admin-page"><div className="admin-page__head"><div><span className="eyebrow">Catalog</span><h1>Categories &amp; brands</h1><p>Keep product taxonomy tidy so new catalog records stay consistent.</p></div><FolderTree size={28} className="admin-page__head-icon" /></div><div className="admin-tabs" role="tablist"><button className={tab === 'categories' ? 'admin-tab admin-tab--active' : 'admin-tab'} type="button" onClick={() => { setTab('categories'); setForm(null); }} role="tab" aria-selected={tab === 'categories'}>Categories</button><button className={tab === 'brands' ? 'admin-tab admin-tab--active' : 'admin-tab'} type="button" onClick={() => { setTab('brands'); setForm(null); }} role="tab" aria-selected={tab === 'brands'}>Brands</button><button className="button button--primary" type="button" onClick={() => setForm({ ...blank })}><Plus size={15} />Add {tab === 'categories' ? 'category' : 'brand'}</button></div>{state.error && <p className="admin-form-error" role="alert"><X size={16} />{state.error}</p>}{state.message && <p className="admin-form-success" role="status"><CheckCircle2 size={16} />{state.message}</p>}{form && <form className="admin-inline-form" onSubmit={save}><label>Name *<input required value={form.name} onChange={update('name')} /></label><label>Slug *<input required pattern="[A-Za-z0-9_-]+" value={form.slug} onChange={update('slug')} /></label>{tab === 'categories' && <label>Description<input value={form.description || ''} onChange={update('description')} /></label>}<label>Order<input type="number" min="0" value={form.sortOrder ?? 0} onChange={update('sortOrder')} /></label><button className="button button--primary" type="submit" disabled={state.status === 'saving'}><Save size={15} />Save</button><button className="button button--outline" type="button" onClick={() => setForm(null)}>Cancel</button></form>} {state.status === 'loading' ? <div className="admin-empty"><p>Loading taxonomy…</p></div> : <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Name</th><th>Slug</th><th>Status</th><th>Order</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{rows.map((item) => <tr key={item.id}><td><strong>{item.name}</strong>{item.description && <small>{item.description}</small>}</td><td>{item.slug}</td><td><span className={'admin-status admin-status--' + item.status}>{item.status}</span></td><td>{item.sortOrder}</td><td><button className="text-link" type="button" onClick={() => setForm({ ...item })}>Edit</button>{item.status !== 'archived' && <button className="text-link text-link--danger" type="button" onClick={() => archive(item.id)}>Archive</button>}</td></tr>)}</tbody></table></div>}</section>;
}
