import { useEffect, useState } from 'react';
import { CheckCircle2, Download, Plus, Save, X } from 'lucide-react';
import { apiGet, apiPatch, apiPost } from '../../lib/apiClient.js';

const blank = { title: '', description: '', category: '', mediaId: '', status: 'draft' };

export default function AdminDownloadsPage() {
  const [rows, setRows] = useState([]);
  const [form, setForm] = useState(null);
  const [state, setState] = useState({ status: 'loading', error: '', message: '' });
  const load = () => apiGet('/api/v1/downloads').then((payload) => { setRows(payload.data || []); setState({ status: 'ready', error: '', message: '' }); }).catch((error) => setState({ status: 'error', error: error.message, message: '' }));
  useEffect(() => { load(); }, []);
  const update = (field) => (event) => setForm((current) => ({ ...current, [field]: event.target.value }));
  const save = async (event) => { event.preventDefault(); setState({ status: 'saving', error: '', message: '' }); try { if (form.id) await apiPatch('/api/v1/downloads/' + form.id, form); else await apiPost('/api/v1/downloads', form); setForm(null); setState({ status: 'saved', error: '', message: 'Download saved.' }); load(); } catch (error) { setState({ status: 'error', error: error.message, message: '' }); } };
  return <section className="admin-page"><div className="admin-page__head"><div><span className="eyebrow">Content</span><h1>Downloads</h1><p>Manage the resource titles and media references shown on the public Downloads page.</p></div><Download size={28} className="admin-page__head-icon" /></div><button className="button button--primary admin-add-inline" type="button" onClick={() => setForm({ ...blank })}><Plus size={15} />Add download</button>{state.error && <p className="admin-form-error" role="alert"><X size={16} />{state.error}</p>}{state.message && <p className="admin-form-success" role="status"><CheckCircle2 size={16} />{state.message}</p>}{form && <form className="admin-inline-form admin-download-form" onSubmit={save}><label>Title *<input required value={form.title} onChange={update('title')} /></label><label>Description<input value={form.description} onChange={update('description')} /></label><label>Category<input value={form.category} onChange={update('category')} /></label><label>Media ID<input type="number" min="1" value={form.mediaId || ''} onChange={update('mediaId')} placeholder="Upload media first" /></label><label>Status<select value={form.status} onChange={update('status')}><option>draft</option><option>published</option><option>archived</option></select></label><button className="button button--primary" type="submit" disabled={state.status === 'saving'}><Save size={15} />Save</button><button className="button button--outline" type="button" onClick={() => setForm(null)}>Cancel</button></form>}{state.status === 'loading' ? <div className="admin-empty"><p>Loading downloads…</p></div> : rows.length === 0 ? <div className="admin-empty"><h2>No resources yet.</h2><p>Add a download after uploading its media asset.</p></div> : <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Title</th><th>Category</th><th>Media</th><th>Status</th><th><span className="sr-only">Action</span></th></tr></thead><tbody>{rows.map((item) => <tr key={item.id}><td><strong>{item.title}</strong><small>{item.description || '—'}</small></td><td>{item.category || '—'}</td><td>{item.mediaName || 'Not attached'}</td><td><span className={'admin-status admin-status--' + item.status}>{item.status}</span></td><td><button className="text-link" type="button" onClick={() => setForm({ ...item })}>Edit</button></td></tr>)}</tbody></table></div>}</section>;
}
