<?php

use App\Http\Controllers\Api\V1\AuthController;
use App\Http\Controllers\Api\V1\ProductController;
use App\Http\Controllers\Api\V1\PageController;
use App\Http\Controllers\Api\V1\LeadController;
use App\Http\Controllers\Api\V1\PublicLeadController;
use App\Http\Controllers\Api\V1\ActivityController;
use App\Http\Controllers\Api\V1\MediaController;
use App\Http\Controllers\Api\V1\SettingsController;
use App\Http\Controllers\Api\V1\PublicSettingsController;
use App\Http\Controllers\Api\V1\TaxonomyController;
use App\Http\Controllers\Api\V1\DownloadController;
use App\Http\Controllers\Api\V1\PublicContentController;
use Illuminate\Support\Facades\Route;

Route::middleware('web')->prefix('v1')->group(function (): void {
    Route::post('/auth/login', [AuthController::class, 'login'])->middleware('throttle:login');
    Route::post('/auth/logout', [AuthController::class, 'logout'])->middleware(['auth:sanctum', 'admin']);
    Route::get('/auth/me', [AuthController::class, 'me'])->middleware(['auth:sanctum', 'admin']);
    Route::get('/public/pages/{page:slug}', [PublicContentController::class, 'page']);
    Route::get('/public/settings', [PublicSettingsController::class, 'show']);
    Route::get('/public/downloads', [DownloadController::class, 'publicIndex']);
    Route::post('/leads', [PublicLeadController::class, 'store']);
    Route::middleware(['auth:sanctum', 'admin'])->group(function (): void {
        Route::get('/catalog/options', [ProductController::class, 'options']);
        Route::get('/taxonomy', [TaxonomyController::class, 'index']);
        Route::post('/taxonomy/{type}', [TaxonomyController::class, 'store'])->whereIn('type', ['brands', 'categories']);
        Route::patch('/taxonomy/{type}/{id}', [TaxonomyController::class, 'update'])->whereIn('type', ['brands', 'categories']);
        Route::post('/taxonomy/{type}/{id}/archive', [TaxonomyController::class, 'archive'])->whereIn('type', ['brands', 'categories']);
        Route::get('/products', [ProductController::class, 'index']);
        Route::post('/products', [ProductController::class, 'store']);
        Route::get('/products/{product}', [ProductController::class, 'show']);
        Route::patch('/products/{product}', [ProductController::class, 'update']);
        Route::post('/products/{product}/publish', [ProductController::class, 'publish']);
        Route::post('/products/{product}/archive', [ProductController::class, 'archive']);
        Route::get('/pages', [PageController::class, 'index']);
        Route::get('/pages/{page}', [PageController::class, 'show']);
        Route::patch('/pages/{page}', [PageController::class, 'update']);
        Route::post('/pages/{page}/sections', [PageController::class, 'storeSection']);
        Route::patch('/page-sections/{pageSection}', [PageController::class, 'updateSection']);
        Route::post('/pages/{page}/publish', [PageController::class, 'publish']);
        Route::post('/pages/{page}/archive', [PageController::class, 'archive']);
        Route::get('/leads', [LeadController::class, 'index']);
        Route::get('/leads/{lead}', [LeadController::class, 'show']);
        Route::patch('/leads/{lead}', [LeadController::class, 'update']);
        Route::post('/leads/{lead}/notes', [LeadController::class, 'note']);
        Route::get('/settings', [SettingsController::class, 'show']);
        Route::patch('/settings', [SettingsController::class, 'update']);
        Route::get('/media', [MediaController::class, 'index']);
        Route::post('/media', [MediaController::class, 'store']);
        Route::post('/media/{mediaAsset}/archive', [MediaController::class, 'archive']);
        Route::get('/activity', [ActivityController::class, 'index']);
        Route::get('/downloads', [DownloadController::class, 'index']);
        Route::post('/downloads', [DownloadController::class, 'store']);
        Route::patch('/downloads/{download}', [DownloadController::class, 'update']);
        Route::post('/downloads/{download}/publish', [DownloadController::class, 'publish']);
        Route::post('/downloads/{download}/archive', [DownloadController::class, 'archive']);
    });
});
