import { ArrowLeft, ArrowRight, Check, ChevronRight, FileText, Phone, ShieldCheck, ShoppingCart } from 'lucide-react';
import { formatNpr, products } from '../data/products.js';

export default function ProductDetailPage({ product, onNavigate, onQuote, onAddToCart }) {
  if (!product) {
    return <main className="detail-page"><div className="container empty-state empty-state--page"><span className="eyebrow">Product not found</span><h1>That product is no longer in this view.</h1><p>Browse the current BLI catalogue to find another security solution.</p><button type="button" className="button button--primary" onClick={() => onNavigate('/products')}>Browse products <ArrowRight size={16} /></button></div></main>;
  }

  const related = products.filter((item) => item.category === product.category && item.id !== product.id).slice(0, 3);

  return (
    <main className="detail-page">
      <div className="container breadcrumbs"><button type="button" onClick={() => onNavigate('/')}>Home</button><ChevronRight size={14} /><button type="button" onClick={() => onNavigate(`/products?category=${encodeURIComponent(product.category)}`)}>{product.category}</button><ChevronRight size={14} /><span>{product.name}</span></div>
      <section className="container detail-layout">
        <div className="detail-gallery"><div className="detail-gallery__main"><img src={product.image} alt={product.imageAlt} /></div><div className="detail-gallery__thumbs"><button type="button" className="detail-thumb detail-thumb--active"><img src={product.image} alt="" /></button></div></div>
        <div className="detail-copy"><span className="eyebrow">{product.brand} · {product.model}</span><h1>{product.name}</h1><p className="detail-description">{product.description}</p><div className="detail-price-row"><strong>{formatNpr(product.price)}</strong><span className={product.quoteOnly ? 'availability availability--quote' : 'availability'}><i />{product.availability}</span></div><div className="detail-spec-pills">{product.shortSpecs.split(' | ').map((spec) => <span key={spec}>{spec}</span>)}</div><div className="detail-actions">{product.quoteOnly ? <button className="button button--primary button--large" type="button" onClick={() => onQuote(product)}><FileText size={18} />Inquiry now</button> : <button className="button button--primary button--large" type="button" onClick={() => onAddToCart(product)}><ShoppingCart size={18} />Inquiry now</button>}<button className="button button--outline button--large" type="button" onClick={() => onQuote(product)}><FileText size={18} />Request quote</button></div><div className="detail-support"><ShieldCheck size={22} /><div><strong>Need help choosing?</strong><p>Share your site requirements and the BLI team can guide the right fit.</p><button className="text-link" type="button" onClick={() => onQuote(product)}>Talk to BLI <ArrowRight size={15} /></button></div></div><a className="detail-call" href="tel:+977-1-XXXXXXX"><Phone size={17} />Call sales for guidance</a></div>
      </section>
      <section className="container detail-info-grid"><div className="detail-panel"><span className="eyebrow">Product information</span><h2>Built for a clearer next step.</h2><p>{product.description} BLI can help you validate compatibility, coverage and installation needs before you commit to a purchase.</p><div className="feature-list">{product.features.map((feature) => <span key={feature}><Check size={16} />{feature}</span>)}</div></div><div className="detail-panel detail-panel--specs"><span className="eyebrow">At a glance</span><h2>Specifications</h2><dl><div><dt>Brand</dt><dd>{product.brand}</dd></div><div><dt>Model</dt><dd>{product.model}</dd></div><div><dt>Category</dt><dd>{product.category}</dd></div><div><dt>Availability</dt><dd>{product.availability}</dd></div></dl></div></section>
      {related.length > 0 && <section className="container related-section"><div className="section-heading"><div><span className="eyebrow">Keep exploring</span><h2>Related products</h2></div><button type="button" className="text-link" onClick={() => onNavigate(`/products?category=${encodeURIComponent(product.category)}`)}>View category <ArrowRight size={16} /></button></div><div className="product-grid product-grid--related">{related.map((item) => <article className="related-card" key={item.id}><img src={item.image} alt={item.imageAlt} /><div><span>{item.brand}</span><strong>{item.name}</strong><button type="button" className="text-link" onClick={() => onNavigate(`/product/${item.slug}`)}>View product <ArrowRight size={14} /></button></div></article>)}</div></section>}
      <div className="container detail-back"><button className="text-link" type="button" onClick={() => onNavigate('/products')}><ArrowLeft size={15} />Back to products</button></div>
    </main>
  );
}
